# Generated by Django 6.0.1 on 2026-01-20 13:42

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_banco', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteInvestidor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('perfil_investidor', models.CharField(choices=[('CONSERVADOR', 'Conservador'), ('MODERADO', 'Moderado'), ('ARROJADO', 'Arrojado')], default='CONSERVADOR', max_length=20)),
                ('patrimonio_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('pessoa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_investidor', to='api_banco.pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='Investimento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_investimento', models.CharField(choices=[('RENDA_FIXA', 'Renda Fixa'), ('ACOES', 'Ações'), ('FUNDOS', 'Fundos'), ('CRIPTO', 'Criptomoedas')], max_length=20)),
                ('valor_investido', models.DecimalField(decimal_places=2, max_digits=15)),
                ('data_aplicacao', models.DateTimeField(auto_now_add=True)),
                ('rentabilidade', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('ativo', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investimentos', to='investimentos.clienteinvestidor')),
            ],
        ),
    ]
