# Generated by Django 6.0.1 on 2026-01-22 12:27

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investimentos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investimento',
            name='rentabilidade',
        ),
        migrations.AddField(
            model_name='investimento',
            name='preco_medio',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AddField(
            model_name='investimento',
            name='quantidade',
            field=models.DecimalField(decimal_places=8, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AddField(
            model_name='investimento',
            name='ticker',
            field=models.CharField(blank=True, help_text='Ex: PETR4, BTC-USD', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='investimento',
            name='tipo_investimento',
            field=models.CharField(choices=[('RENDA_FIXA', 'Renda Fixa'), ('ACOES', 'Ações'), ('FUNDOS', 'Fundos Imobiliários (FIIs)'), ('CRIPTO', 'Criptomoedas')], max_length=20),
        ),
    ]
